# Generated by Django 4.1.12 on 2024-04-25 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_customers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customers',
            new_name='customer',
        ),
    ]
