# Generated by Django 4.1.12 on 2024-04-29 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_rename_customers_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='username',
        ),
    ]
